<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Low Stock Notification</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }
        .header {
            background-color: #f8f9fa;
            padding: 20px;
            border-radius: 5px;
            margin-bottom: 20px;
        }
        .alert {
            background-color: #fff3cd;
            border: 1px solid #ffc107;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
        }
        .product-info {
            background-color: #f8f9fa;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
        }
        .product-image {
            max-width: 200px;
            height: auto;
            border-radius: 5px;
            margin-bottom: 10px;
        }
        .stock-warning {
            color: #dc3545;
            font-weight: bold;
            font-size: 18px;
        }
        .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            font-size: 12px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>⚠️ Low Stock Notification</h1>
    </div>

    <div class="alert">
        <strong>Warning:</strong> A product has low stock and requires your attention.
    </div>

    <div class="product-info">
        <h2>{{ $product->name }}</h2>
        
        @if($product->image_url)
        <img src="{{ $product->image_url }}" alt="{{ $product->name }}" class="product-image">
        @endif

        <p><strong>Current Stock:</strong> <span class="stock-warning">{{ $product->stock }} units</span></p>
        <p><strong>Price:</strong> ${{ number_format($product->price, 2, '.', ',') }}</p>
        <p><strong>Notification Date:</strong> {{ now()->format('M d, Y at H:i') }}</p>
    </div>

    <p>
        The product <strong>{{ $product->name }}</strong> has stock below 10 units. 
        Please restock this product as soon as possible to avoid stockout.
    </p>

    <div class="footer">
        <p>This is an automated email generated by the stock management system.</p>
        <p>&copy; {{ date('Y') }} ShopCart - All rights reserved</p>
    </div>
</body>
</html>
